# Generated by Django 2.1.7 on 2019-10-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servdou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chengyu',
            name='pos',
            field=models.IntegerField(default=13),
        ),
    ]
